// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjEpQcGPbY3Dg2rSfKOpbF79OdWJDPGdQ',
    appId: '1:109225475040:web:c7c367bd77d74183478985',
    messagingSenderId: '109225475040',
    projectId: 'housingservices-ad8cb',
    authDomain: 'housingservices-ad8cb.firebaseapp.com',
    databaseURL: 'https://housingservices-ad8cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'housingservices-ad8cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-dQjWmxZ_8zpbNCm1-eTXf7iZjRPzmA',
    appId: '1:109225475040:android:f888a4a0cc240999478985',
    messagingSenderId: '109225475040',
    projectId: 'housingservices-ad8cb',
    databaseURL: 'https://housingservices-ad8cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'housingservices-ad8cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVl3aefsN2Qvds4uq-U96I9ZS8QJa9r7w',
    appId: '1:109225475040:ios:6ec2bd4eca85c910478985',
    messagingSenderId: '109225475040',
    projectId: 'housingservices-ad8cb',
    databaseURL: 'https://housingservices-ad8cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'housingservices-ad8cb.appspot.com',
    iosClientId: '109225475040-dc8jnvgh5uams119mncnospejat922i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.housingEstateServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVl3aefsN2Qvds4uq-U96I9ZS8QJa9r7w',
    appId: '1:109225475040:ios:6ec2bd4eca85c910478985',
    messagingSenderId: '109225475040',
    projectId: 'housingservices-ad8cb',
    databaseURL: 'https://housingservices-ad8cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'housingservices-ad8cb.appspot.com',
    iosClientId: '109225475040-dc8jnvgh5uams119mncnospejat922i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.housingEstateServices',
  );
}
